services:
  - type: web
    name: kanban-backend
    env: python
    rootDir: kanban_backend
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && daphne -b 0.0.0.0 -p $PORT kanban_backend.asgi:application
    autoDeploy: true
